Handle all the imports 

In [ ]:
# We are at: 
# ACTIVE/fbpic/LASYFB/NewWavefronts.ipynb

import sys
import os
from importlib import reload
from collections import OrderedDict

import numpy as np
import matplotlib.pyplot as plt

import torch
import torch.nn as nn
import torch.optim as optim
from torchvision import transforms

sys.path.insert(0, '../../../CNN/Old/ML/src/generation/') 
import utility_fnc
reload(utility_fnc)
from train import *
from ssim import compute_ssim_numpy
from criterion import *

import dataset as ds

Load the experimental spots

In [ ]:

# sys.path.insert(0, '../../../CNN/Old/ML/src/generation/')
trn_dir='../../../CNN/Old/ML/src/generation/'
data_dir = trn_dir+'Real3/'
# data_dir = trn_dir+'temp_2/'

#     resize, normalize_to
SetSz = len(os.listdir(data_dir))
print(SetSz)
dataset_size = 200 #SetSz #loading real dataset
dataset = ds.psf_dataset(root_dir = data_dir, 
                      size = dataset_size,
                      transform = transforms.Compose([ToTensor(), utility_fnc.resize()])) #Normalize(), 

Reload Models


In [ ]:
# Load model architectures and weights
import json
from Flex import U1
from U1D import U1

device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
device='cpu'

model_dir =trn_dir+'mod_PIL_total_/modelfinal.pth' # model path
state_dict = torch.load(model_dir, map_location='cpu')
new_state_dict = OrderedDict()

from U1D_dropout import U1_drop

dropout=0.012 # from 0.02 (put in value used here)
dropout_bottleneck=0.02 # from 0.07 (put in value used here)
model = U1_drop(1, 1, dropout_enc=dropout_bottleneck,dropout_bottleneck=dropout_bottleneck,dropout_dec=dropout_bottleneck).to(device)

# model = U1(1, 1) #.to(device)
for k, v in state_dict.items():
    name = k[7:] # remove module.
    new_state_dict[name] = v
model.load_state_dict(state_dict)

Testing on old Data Set


In [6]:
 
import torch.nn as nn    
import utility_fnc
reload(utility_fnc)

idds=np.arange(0, 50)

device='cpu'
lasers=[]
phs=[]
dif=[]
rms=[]
MSE=[]
mse=nn.MSELoss()
SSIM=[]
mnMx=[]
for id_ in idds:
            d=dataset[id_]
            img = torch.as_tensor(d['image']) #.unsqueeze(0)d['phase']
            print(img)
            print(np.shape(img), print(img.max()))
#             utility_fnc.plotter(img)
            vmax=img.max()
            vmin=img.min()
            
            norm1 = (img - torch.min(img)) / (torch.max(img) - torch.min(img))
#             utility_fnc.plotter(norm1)
            output = model(norm1.unsqueeze(0).unsqueeze(0))
            phase_est = output[0].detach().to('cpu').numpy()
            phs.append(phase_est)
            phase=0.8*phase_est/(2*np.pi)
            dif.append(np.max(phase)-np.min(phase))
            rms.append(np.sqrt(np.mean((phase*(0.8*1e-6)/(2*np.pi))**2)))
            print(1e6*np.max(phase*(0.8*1e-6)/(2*np.pi)))
            print(1e6*np.min(phase*(0.8*1e-6)/(2*np.pi)))
            print('rms', rms[-1])
            mnMx.append(1e6*np.max(phase*(0.8*1e-6)/(2*np.pi))-1e6*np.min(phase*(0.8*1e-6)/(2*np.pi)))
            
            
            I_pred, las_obj=utility_fnc.propagator(phase_est[0], f0=9)
            img2=I_pred.squeeze(0).squeeze(0).detach().cpu().numpy()**2
            norm = (img2 - np.min(img2)) / (np.max(img2) - np.min(img2))
            utility_fnc.plotter(norm) #, vmin=vmin, vmax=vmax)
            utility_fnc.plotter(phase.squeeze(0))   
            lasers.append(las_obj)
            print(np.shape(norm), np.shape(norm1))
            npNorm=norm
            pdNorm=np.pad(npNorm, ((3, 3), (3, 3)))
            plt.imshow(pdNorm)
            plt.show()
            norm1=utility_fnc.pad_and_resize(norm1, np.shape(pdNorm))
            img=utility_fnc.pad_and_resize(img, np.shape(norm))
            plt.show()
            img[img==0]==1
            print(img.squeeze(0).squeeze(0))
#             utility_fnc.plotter(np.sqrt(img.squeeze(0).squeeze(0))) #, vmin=vmin, vmax=vmax)
#             utility_fnc.plotter(np.sqrt(img2))
#             norm = (img2 - np.min(img2)) / (np.max(img2) - np.min(img2))
            #norm1=np.pad(norm1, pad_width=((),()))
            MSE.append(mse(torch.as_tensor(norm1), torch.as_tensor(pdNorm)))
            print(np.shape(norm1), np.shape(norm))
#             npNorm=norm
#             pdNorm=np.pad(npNorm, ((10, 10), (10, 10)))
#             plt.imshow(pdNorm)
#             plt.show()
            
            norm1=utility_fnc.pad_and_resize(norm1, np.shape(pdNorm))
            SSIM.append(compute_ssim_numpy(norm1.squeeze().squeeze().numpy(), pdNorm))
            print(SSIM[-1])


/var/tmp/pbs.1816038.pbs/ipykernel_2291810/4247516163.py:18: ResourceWarning: unclosed file <_io.BufferedReader name='../../../CNN/Old/ML/src/generation/Real3/psf_0.fits'>
  d=dataset[id_]


tensor([[ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ..., -4.2625e+14,
         -2.4357e+14,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  3.0446e+14,
          7.9160e+14,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ..., -3.6536e+14,
          6.0893e+13,  0.0000e+00],
        ...,
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  0.0000e+00,
          0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  0.0000e+00,
          0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  0.0000e+00,
          0.0000e+00,  0.0000e+00]])
tensor(3.9580e+15)
torch.Size([256, 280]) None
0.12294664486489637
-0.3196923614723346
rms 9.106549e-08
tensor([[0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        ...,
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.]])
tensor(5.4

/var/tmp/pbs.1816038.pbs/ipykernel_2291810/4247516163.py:18: ResourceWarning: unclosed file <_io.BufferedReader name='../../../CNN/Old/ML/src/generation/Real3/psf_1.fits'>
  d=dataset[id_]


0.10499531555296926
-0.29529670086958504
rms 8.441644e-08
tensor([[ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  3.5165e+14,
         -1.4066e+14, -2.8132e+14],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ..., -7.0330e+13,
         -6.3297e+14,  7.0330e+13],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ..., -2.1099e+14,
         -3.5165e+14,  7.0330e+14],
        ...,
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  0.0000e+00,
          0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  0.0000e+00,
          0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  0.0000e+00,
          0.0000e+00,  0.0000e+00]])
tensor(8.3833e+16)
torch.Size([256, 256]) None


/var/tmp/pbs.1816038.pbs/ipykernel_2291810/4247516163.py:18: ResourceWarning: unclosed file <_io.BufferedReader name='../../../CNN/Old/ML/src/generation/Real3/psf_2.fits'>
  d=dataset[id_]


0.08128844086741083
-0.34832117989935796
rms 8.917757e-08
tensor([[ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  1.6859e+14,
          4.2148e+13,  5.4792e+14],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ..., -2.9504e+14,
         -8.8511e+14, -4.2148e+13],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  0.0000e+00,
         -3.3718e+14, -4.2148e+13],
        ...,
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  0.0000e+00,
          0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  0.0000e+00,
          0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  0.0000e+00,
          0.0000e+00,  0.0000e+00]])
tensor(3.0094e+16)
torch.Size([256, 256]) None


/var/tmp/pbs.1816038.pbs/ipykernel_2291810/4247516163.py:18: ResourceWarning: unclosed file <_io.BufferedReader name='../../../CNN/Old/ML/src/generation/Real3/psf_3.fits'>
  d=dataset[id_]


0.10075586942548398
-0.30319520760713203
rms 8.3100204e-08
tensor([[ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ..., -4.6732e+14,
          6.6760e+13, -6.6760e+13],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ..., -9.3464e+14,
         -1.0014e+15, -8.0112e+14],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ..., -2.6704e+14,
         -3.3380e+14, -1.5355e+15],
        ...,
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  0.0000e+00,
          0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  0.0000e+00,
          0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  0.0000e+00,
          0.0000e+00,  0.0000e+00]])
tensor(4.1525e+16)
torch.Size([256, 256]) None


/var/tmp/pbs.1816038.pbs/ipykernel_2291810/4247516163.py:18: ResourceWarning: unclosed file <_io.BufferedReader name='../../../CNN/Old/ML/src/generation/Real3/psf_4.fits'>
  d=dataset[id_]


0.08133076789818006
-0.36625354482566763
rms 8.6410296e-08
tensor([[ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ..., -9.0268e+14,
          3.0089e+14, -7.5224e+14],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ..., -6.0179e+14,
         -1.1284e+15, -3.0089e+14],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ..., -5.2656e+14,
          7.5224e+13, -3.0089e+14],
        ...,
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  0.0000e+00,
          0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  0.0000e+00,
          0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  0.0000e+00,
          0.0000e+00,  0.0000e+00]])
tensor(8.9215e+16)
torch.Size([256, 256]) None


/var/tmp/pbs.1816038.pbs/ipykernel_2291810/4247516163.py:18: ResourceWarning: unclosed file <_io.BufferedReader name='../../../CNN/Old/ML/src/generation/Real3/psf_5.fits'>
  d=dataset[id_]


0.0926856529304132
-0.30981266263552243
rms 8.4924885e-08
tensor([[ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ..., -4.8393e+14,
          4.8393e+14,  1.3827e+14],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ..., -5.5307e+14,
          4.1480e+14,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ..., -9.6787e+14,
          1.3827e+14, -1.7283e+15],
        ...,
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  0.0000e+00,
          0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  0.0000e+00,
          0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  0.0000e+00,
          0.0000e+00,  0.0000e+00]])
tensor(5.8556e+16)
torch.Size([256, 256]) None


/var/tmp/pbs.1816038.pbs/ipykernel_2291810/4247516163.py:18: ResourceWarning: unclosed file <_io.BufferedReader name='../../../CNN/Old/ML/src/generation/Real3/psf_6.fits'>
  d=dataset[id_]


0.06571459465476437
-0.3100370804531849
rms 9.040041e-08
tensor([[ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ..., -1.2989e+14,
         -1.9483e+14, -1.1040e+15],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  6.4944e+13,
          6.4944e+13, -6.4944e+13],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ..., -2.5978e+14,
         -1.2989e+14,  3.2472e+14],
        ...,
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  0.0000e+00,
          0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  0.0000e+00,
          0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  0.0000e+00,
          0.0000e+00,  0.0000e+00]])
tensor(4.9487e+16)
torch.Size([256, 256]) None


/var/tmp/pbs.1816038.pbs/ipykernel_2291810/4247516163.py:18: ResourceWarning: unclosed file <_io.BufferedReader name='../../../CNN/Old/ML/src/generation/Real3/psf_7.fits'>
  d=dataset[id_]


0.1214671669913514
-0.32947033901109535
rms 8.880791e-08
tensor([[ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ..., -5.0786e+14,
          7.6179e+14, -1.6929e+14],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ..., -3.3857e+14,
         -2.5393e+14, -8.4643e+13],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ..., -2.5393e+14,
          5.0786e+14, -1.6929e+14],
        ...,
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  0.0000e+00,
          0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  0.0000e+00,
          0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  0.0000e+00,
          0.0000e+00,  0.0000e+00]])
tensor(1.0589e+17)
torch.Size([256, 256]) None


/var/tmp/pbs.1816038.pbs/ipykernel_2291810/4247516163.py:18: ResourceWarning: unclosed file <_io.BufferedReader name='../../../CNN/Old/ML/src/generation/Real3/psf_8.fits'>
  d=dataset[id_]


0.07380385369515352
-0.37018727994109213
rms 9.035924e-08
tensor([[ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ..., -5.2072e+14,
         -1.9527e+14, -3.9054e+14],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ..., -9.1126e+14,
         -6.5090e+14, -3.9054e+14],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ..., -7.8108e+14,
         -7.8108e+14, -1.9527e+14],
        ...,
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  0.0000e+00,
          0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  0.0000e+00,
          0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  0.0000e+00,
          0.0000e+00,  0.0000e+00]])
tensor(9.2948e+16)
torch.Size([256, 256]) None


/var/tmp/pbs.1816038.pbs/ipykernel_2291810/4247516163.py:18: ResourceWarning: unclosed file <_io.BufferedReader name='../../../CNN/Old/ML/src/generation/Real3/psf_9.fits'>
  d=dataset[id_]


0.0802494355411909
-0.3199367029083078
rms 8.9024304e-08
tensor([[ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ..., -8.8512e+14,
         -3.4043e+14, -4.7660e+14],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ..., -5.4469e+14,
         -4.7660e+14, -5.4469e+14],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ..., -1.0213e+15,
          8.1703e+14, -1.0213e+15],
        ...,
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  0.0000e+00,
          0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  0.0000e+00,
          0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  0.0000e+00,
          0.0000e+00,  0.0000e+00]])
tensor(6.0937e+16)
torch.Size([256, 256]) None


/var/tmp/pbs.1816038.pbs/ipykernel_2291810/4247516163.py:18: ResourceWarning: unclosed file <_io.BufferedReader name='../../../CNN/Old/ML/src/generation/Real3/psf_10.fits'>
  d=dataset[id_]


0.08172821708285483
-0.3352216424445942
rms 8.5513996e-08
tensor([[ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ..., -5.5227e+14,
          1.3807e+14, -4.1421e+14],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  1.2426e+15,
         -2.7614e+14, -2.7614e+14],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  2.7614e+14,
          5.5227e+14,  0.0000e+00],
        ...,
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  0.0000e+00,
          0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  0.0000e+00,
          0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  0.0000e+00,
          0.0000e+00,  0.0000e+00]])
tensor(2.5225e+17)
torch.Size([256, 256]) None


/var/tmp/pbs.1816038.pbs/ipykernel_2291810/4247516163.py:18: ResourceWarning: unclosed file <_io.BufferedReader name='../../../CNN/Old/ML/src/generation/Real3/psf_11.fits'>
  d=dataset[id_]


0.07260816659027114
-0.3552184750788001
rms 9.140028e-08
tensor([[ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ..., -1.4105e+15,
          9.8734e+14,  8.4629e+14],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ..., -1.1284e+15,
         -1.2694e+15,  4.2314e+14],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  1.6926e+15,
         -1.1284e+15,  2.8210e+14],
        ...,
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  0.0000e+00,
          0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  0.0000e+00,
          0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  0.0000e+00,
          0.0000e+00,  0.0000e+00]])
tensor(3.2131e+17)
torch.Size([256, 256]) None


/var/tmp/pbs.1816038.pbs/ipykernel_2291810/4247516163.py:18: ResourceWarning: unclosed file <_io.BufferedReader name='../../../CNN/Old/ML/src/generation/Real3/psf_12.fits'>
  d=dataset[id_]


0.08148872154833953
-0.31167368774731585
rms 8.558711e-08
tensor([[ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  1.7161e+15,
         -9.2405e+14,  5.2803e+14],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ..., -1.3201e+15,
          0.0000e+00, -7.9205e+14],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  2.6402e+15,
         -7.9205e+14,  2.9042e+15],
        ...,
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  0.0000e+00,
          0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  0.0000e+00,
          0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  0.0000e+00,
          0.0000e+00,  0.0000e+00]])
tensor(2.1200e+17)
torch.Size([256, 256]) None


/var/tmp/pbs.1816038.pbs/ipykernel_2291810/4247516163.py:18: ResourceWarning: unclosed file <_io.BufferedReader name='../../../CNN/Old/ML/src/generation/Real3/psf_13.fits'>
  d=dataset[id_]


0.06805701247003526
-0.32344846090381907
rms 8.4248555e-08
tensor([[ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  0.0000e+00,
          0.0000e+00,  1.9256e+15],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  2.4508e+15,
          7.0023e+14,  3.6762e+15],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ..., -2.8009e+15,
         -5.2518e+14,  2.4508e+15],
        ...,
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  0.0000e+00,
          0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  0.0000e+00,
          0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  0.0000e+00,
          0.0000e+00,  0.0000e+00]])
tensor(2.8237e+17)
torch.Size([256, 256]) None


/var/tmp/pbs.1816038.pbs/ipykernel_2291810/4247516163.py:18: ResourceWarning: unclosed file <_io.BufferedReader name='../../../CNN/Old/ML/src/generation/Real3/psf_14.fits'>
  d=dataset[id_]


0.08336013479492976
-0.31935653055370494
rms 8.921785e-08
tensor([[ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ..., -2.0094e+14,
          1.0047e+15, -2.0094e+14],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ..., -1.0047e+15,
         -4.0189e+14,  4.0189e+14],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  0.0000e+00,
         -2.4113e+15,  1.6076e+15],
        ...,
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  0.0000e+00,
          0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  0.0000e+00,
          0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  0.0000e+00,
          0.0000e+00,  0.0000e+00]])
tensor(5.5059e+17)
torch.Size([256, 256]) None


/var/tmp/pbs.1816038.pbs/ipykernel_2291810/4247516163.py:18: ResourceWarning: unclosed file <_io.BufferedReader name='../../../CNN/Old/ML/src/generation/Real3/psf_15.fits'>
  d=dataset[id_]


0.06961560927720711
-0.3538260102686763
rms 8.826771e-08
tensor([[ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  0.0000e+00,
         -1.5206e+15,  1.9768e+15],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ..., -6.0825e+14,
          4.5619e+14,  1.2165e+15],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  1.0644e+15,
         -9.1237e+14,  4.5619e+14],
        ...,
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  0.0000e+00,
          0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  0.0000e+00,
          0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  0.0000e+00,
          0.0000e+00,  0.0000e+00]])
tensor(2.0741e+17)
torch.Size([256, 256]) None


/var/tmp/pbs.1816038.pbs/ipykernel_2291810/4247516163.py:18: ResourceWarning: unclosed file <_io.BufferedReader name='../../../CNN/Old/ML/src/generation/Real3/psf_16.fits'>
  d=dataset[id_]


0.07335304985645053
-0.3208565431123134
rms 9.0690456e-08
tensor([[ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  1.7590e+15,
         -2.1988e+15,  3.9578e+15],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ..., -2.1988e+14,
         -1.3193e+15, -1.5392e+15],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  1.9789e+15,
         -8.7951e+14, -1.5392e+15],
        ...,
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  0.0000e+00,
          0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  0.0000e+00,
          0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  0.0000e+00,
          0.0000e+00,  0.0000e+00]])
tensor(4.8439e+17)
torch.Size([256, 256]) None


/var/tmp/pbs.1816038.pbs/ipykernel_2291810/4247516163.py:18: ResourceWarning: unclosed file <_io.BufferedReader name='../../../CNN/Old/ML/src/generation/Real3/psf_17.fits'>
  d=dataset[id_]


0.0598321960865178
-0.31349625828624994
rms 8.6527244e-08
tensor([[ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ..., -1.9276e+15,
          1.2048e+15, -1.9276e+15],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ..., -1.4457e+15,
         -1.4457e+15, -2.8914e+15],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ..., -2.4095e+15,
         -1.9276e+15,  2.4095e+14],
        ...,
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  0.0000e+00,
          0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  0.0000e+00,
          0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  0.0000e+00,
          0.0000e+00,  0.0000e+00]])
tensor(5.0672e+17)
torch.Size([256, 256]) None


/var/tmp/pbs.1816038.pbs/ipykernel_2291810/4247516163.py:18: ResourceWarning: unclosed file <_io.BufferedReader name='../../../CNN/Old/ML/src/generation/Real3/psf_18.fits'>
  d=dataset[id_]


0.07696298354176179
-0.32886563872125407
rms 8.78054e-08
tensor([[ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ..., -2.7693e+14,
         -1.1077e+15,  1.3847e+15],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  2.2155e+15,
          2.2155e+15, -5.5387e+14],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  1.3016e+16,
          5.5387e+14, -2.7693e+14],
        ...,
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  0.0000e+00,
          0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  0.0000e+00,
          0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  0.0000e+00,
          0.0000e+00,  0.0000e+00]])
tensor(6.8874e+17)
torch.Size([256, 256]) None


/var/tmp/pbs.1816038.pbs/ipykernel_2291810/4247516163.py:18: ResourceWarning: unclosed file <_io.BufferedReader name='../../../CNN/Old/ML/src/generation/Real3/psf_19.fits'>
  d=dataset[id_]


0.07844604255069498
-0.2751498016095866
rms 8.6853355e-08
tensor([[ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ..., -1.5314e+15,
         -3.0629e+14,  5.8194e+15],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ..., -2.4503e+15,
         -2.4503e+15, -4.5943e+15],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  3.0629e+14,
          2.4503e+15,  6.1257e+14],
        ...,
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  0.0000e+00,
          0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  0.0000e+00,
          0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  0.0000e+00,
          0.0000e+00,  0.0000e+00]])
tensor(9.7613e+17)
torch.Size([256, 256]) None


/var/tmp/pbs.1816038.pbs/ipykernel_2291810/4247516163.py:18: ResourceWarning: unclosed file <_io.BufferedReader name='../../../CNN/Old/ML/src/generation/Real3/psf_20.fits'>
  d=dataset[id_]


0.07158598691603402
-0.3468816487384174
rms 9.0217114e-08
tensor([[ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  2.2958e+15,
          3.8264e+14,  1.9132e+14],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  0.0000e+00,
         -2.8698e+15,  7.6527e+14],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  9.5659e+14,
          2.8698e+15, -2.6785e+15],
        ...,
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  0.0000e+00,
          0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  0.0000e+00,
          0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  0.0000e+00,
          0.0000e+00,  0.0000e+00]])
tensor(5.1235e+17)
torch.Size([256, 256]) None


/var/tmp/pbs.1816038.pbs/ipykernel_2291810/4247516163.py:18: ResourceWarning: unclosed file <_io.BufferedReader name='../../../CNN/Old/ML/src/generation/Real3/psf_21.fits'>
  d=dataset[id_]


0.07557534331681381
-0.34098755463674024
rms 9.0522626e-08
tensor([[ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  1.0899e+13,
          0.0000e+00, -8.7188e+13],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ..., -4.3594e+14,
          1.5258e+14, -5.4493e+13],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  2.1797e+14,
         -1.0899e+13, -1.0899e+13],
        ...,
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  0.0000e+00,
          0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  0.0000e+00,
          0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  0.0000e+00,
          0.0000e+00,  0.0000e+00]])
tensor(7.4110e+14)
torch.Size([256, 256]) None


/var/tmp/pbs.1816038.pbs/ipykernel_2291810/4247516163.py:18: ResourceWarning: unclosed file <_io.BufferedReader name='../../../CNN/Old/ML/src/generation/Real3/psf_22.fits'>
  d=dataset[id_]


0.1292204103719996
-0.3593432609250158
rms 8.794667e-08
tensor([[ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ..., -3.2656e+14,
          2.4492e+15,  1.6328e+14],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ..., -1.3062e+15,
          2.2859e+15, -1.7961e+15],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  2.1226e+15,
          6.5312e+14, -2.6125e+15],
        ...,
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  0.0000e+00,
          0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  0.0000e+00,
          0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  0.0000e+00,
          0.0000e+00,  0.0000e+00]])
tensor(4.3922e+17)
torch.Size([256, 256]) None


/var/tmp/pbs.1816038.pbs/ipykernel_2291810/4247516163.py:18: ResourceWarning: unclosed file <_io.BufferedReader name='../../../CNN/Old/ML/src/generation/Real3/psf_23.fits'>
  d=dataset[id_]


0.0594254174757225
-0.29412277058327163
rms 8.187472e-08
tensor([[ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ..., -1.3472e+15,
          2.2454e+15,  1.3472e+15],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ..., -1.3472e+15,
          7.8589e+15, -6.7362e+14],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  1.1227e+15,
          2.4699e+15,  3.5927e+15],
        ...,
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  0.0000e+00,
          0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  0.0000e+00,
          0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  0.0000e+00,
          0.0000e+00,  0.0000e+00]])
tensor(7.4143e+17)
torch.Size([256, 256]) None


/var/tmp/pbs.1816038.pbs/ipykernel_2291810/4247516163.py:18: ResourceWarning: unclosed file <_io.BufferedReader name='../../../CNN/Old/ML/src/generation/Real3/psf_24.fits'>
  d=dataset[id_]


0.07008744518088861
-0.2979069222419639
rms 8.694555e-08
tensor([[ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  4.0823e+15,
         -5.1029e+14,  1.0206e+15],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  3.5721e+15,
          3.0618e+15,  1.0206e+16],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ..., -2.5515e+15,
          1.0206e+15, -1.0206e+15],
        ...,
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  0.0000e+00,
          0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  0.0000e+00,
          0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  0.0000e+00,
          0.0000e+00,  0.0000e+00]])
tensor(2.5163e+18)
torch.Size([256, 256]) None


/var/tmp/pbs.1816038.pbs/ipykernel_2291810/4247516163.py:18: ResourceWarning: unclosed file <_io.BufferedReader name='../../../CNN/Old/ML/src/generation/Real3/psf_25.fits'>
  d=dataset[id_]


0.06364948745840593
-0.2977662347802834
rms 8.6409756e-08
tensor([[ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  3.3127e+15,
          1.6564e+15,  6.6254e+15],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  8.8339e+15,
         -1.1042e+15,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  2.2085e+15,
         -7.7297e+15,  8.2818e+15],
        ...,
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  0.0000e+00,
          0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  0.0000e+00,
          0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  0.0000e+00,
          0.0000e+00,  0.0000e+00]])
tensor(2.7501e+18)
torch.Size([256, 256]) None


/var/tmp/pbs.1816038.pbs/ipykernel_2291810/4247516163.py:18: ResourceWarning: unclosed file <_io.BufferedReader name='../../../CNN/Old/ML/src/generation/Real3/psf_26.fits'>
  d=dataset[id_]


0.06528564711061335
-0.3165323789744434
rms 8.849204e-08
tensor([[ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  6.4551e+15,
         -1.5844e+16,  1.1150e+16],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  9.9760e+15,
         -3.5209e+15,  5.8682e+14],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  7.0419e+15,
         -8.8024e+15,  1.2910e+16],
        ...,
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  0.0000e+00,
          0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  0.0000e+00,
          0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  0.0000e+00,
          0.0000e+00,  0.0000e+00]])
tensor(2.8402e+18)
torch.Size([256, 256]) None


/var/tmp/pbs.1816038.pbs/ipykernel_2291810/4247516163.py:18: ResourceWarning: unclosed file <_io.BufferedReader name='../../../CNN/Old/ML/src/generation/Real3/psf_27.fits'>
  d=dataset[id_]


0.06273141650581238
-0.3081600254972727
rms 9.0113836e-08
tensor([[ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  0.0000e+00,
          4.6290e+15,  2.8931e+15],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ..., -4.0503e+15,
         -7.5221e+15,  1.1572e+15],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ..., -5.2076e+15,
          1.1572e+15,  2.3145e+15],
        ...,
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  0.0000e+00,
          0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  0.0000e+00,
          0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  0.0000e+00,
          0.0000e+00,  0.0000e+00]])
tensor(2.6414e+18)
torch.Size([256, 256]) None


/var/tmp/pbs.1816038.pbs/ipykernel_2291810/4247516163.py:18: ResourceWarning: unclosed file <_io.BufferedReader name='../../../CNN/Old/ML/src/generation/Real3/psf_28.fits'>
  d=dataset[id_]


0.06205032576644953
-0.27902959232051217
rms 8.6760195e-08
tensor([[ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ..., -1.8669e+15,
         -4.6672e+15,  4.2005e+15],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  1.6802e+16,
          2.8003e+15,  1.4002e+15],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  2.3336e+15,
          0.0000e+00, -9.3344e+14],
        ...,
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  0.0000e+00,
          0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  0.0000e+00,
          0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  0.0000e+00,
          0.0000e+00,  0.0000e+00]])
tensor(2.6080e+18)
torch.Size([256, 256]) None


/var/tmp/pbs.1816038.pbs/ipykernel_2291810/4247516163.py:18: ResourceWarning: unclosed file <_io.BufferedReader name='../../../CNN/Old/ML/src/generation/Real3/psf_29.fits'>
  d=dataset[id_]


0.06657493401007741
-0.28721686362587207
rms 8.748803e-08
tensor([[ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  2.6463e+15,
          1.2570e+16, -9.2620e+15],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  3.9694e+15,
         -1.3231e+15,  8.6004e+15],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  5.2926e+15,
         -6.6157e+14, -4.6310e+15],
        ...,
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  0.0000e+00,
          0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  0.0000e+00,
          0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  0.0000e+00,
          0.0000e+00,  0.0000e+00]])
tensor(2.6125e+18)
torch.Size([256, 256]) None


/var/tmp/pbs.1816038.pbs/ipykernel_2291810/4247516163.py:18: ResourceWarning: unclosed file <_io.BufferedReader name='../../../CNN/Old/ML/src/generation/Real3/psf_30.fits'>
  d=dataset[id_]


0.07249077071946886
-0.3217660093923769
rms 8.939719e-08
tensor([[ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  8.0833e+15,
         -8.9814e+15,  8.9814e+15],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ..., -4.4907e+15,
          4.4907e+15, -8.9814e+14],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  4.4907e+15,
         -4.4907e+15, -2.6944e+15],
        ...,
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  0.0000e+00,
          0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  0.0000e+00,
          0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  0.0000e+00,
          0.0000e+00,  0.0000e+00]])
tensor(6.3400e+18)
torch.Size([256, 256]) None


/var/tmp/pbs.1816038.pbs/ipykernel_2291810/4247516163.py:18: ResourceWarning: unclosed file <_io.BufferedReader name='../../../CNN/Old/ML/src/generation/Real3/psf_31.fits'>
  d=dataset[id_]


0.0892612916914004
-0.2843302127075731
rms 7.950289e-08
tensor([[ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  6.5684e+15,
         -3.6491e+15,  1.4596e+16],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  3.6491e+15,
         -8.7578e+15, -8.0280e+15],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  1.0217e+16,
          2.1895e+15, -5.8386e+15],
        ...,
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  0.0000e+00,
          0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  0.0000e+00,
          0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  0.0000e+00,
          0.0000e+00,  0.0000e+00]])
tensor(3.8075e+18)
torch.Size([256, 256]) None


/var/tmp/pbs.1816038.pbs/ipykernel_2291810/4247516163.py:18: ResourceWarning: unclosed file <_io.BufferedReader name='../../../CNN/Old/ML/src/generation/Real3/psf_32.fits'>
  d=dataset[id_]


0.07437918014829847
-0.333683544795349
rms 8.7822606e-08
tensor([[ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ..., -5.0171e+15,
          0.0000e+00, -4.3900e+15],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ..., -1.8814e+15,
          1.1288e+16,  1.6933e+16],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ..., -6.2714e+14,
         -3.7628e+15,  6.8985e+15],
        ...,
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  0.0000e+00,
          0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  0.0000e+00,
          0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  0.0000e+00,
          0.0000e+00,  0.0000e+00]])
tensor(3.2373e+18)
torch.Size([256, 256]) None


/var/tmp/pbs.1816038.pbs/ipykernel_2291810/4247516163.py:18: ResourceWarning: unclosed file <_io.BufferedReader name='../../../CNN/Old/ML/src/generation/Real3/psf_33.fits'>
  d=dataset[id_]


0.060871215623592434
-0.3152790952754003
rms 8.966836e-08
tensor([[ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  1.0554e+16,
          6.0308e+15,  1.2815e+16],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ..., -3.0154e+15,
         -7.5384e+15,  6.0308e+15],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ..., -6.7846e+15,
         -9.8000e+15,  3.0154e+15],
        ...,
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  0.0000e+00,
          0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  0.0000e+00,
          0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  0.0000e+00,
          0.0000e+00,  0.0000e+00]])
tensor(4.0346e+18)
torch.Size([256, 256]) None


/var/tmp/pbs.1816038.pbs/ipykernel_2291810/4247516163.py:18: ResourceWarning: unclosed file <_io.BufferedReader name='../../../CNN/Old/ML/src/generation/Real3/psf_34.fits'>
  d=dataset[id_]


0.06357262805067876
-0.3438569819991244
rms 8.960596e-08
tensor([[0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        ...,
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.]])
tensor(7.2061e+14)
torch.Size([256, 256]) None


/var/tmp/pbs.1816038.pbs/ipykernel_2291810/4247516163.py:18: ResourceWarning: unclosed file <_io.BufferedReader name='../../../CNN/Old/ML/src/generation/Real3/psf_35.fits'>
  d=dataset[id_]


0.13912747931499325
-0.35370806017454015
rms 9.1352696e-08
tensor([[ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  0.0000e+00,
          4.4230e+15,  1.1610e+16],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  1.1058e+15,
         -4.4230e+15, -5.5288e+14],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  1.1610e+16,
          1.0505e+16, -2.7644e+15],
        ...,
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  0.0000e+00,
          0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  0.0000e+00,
          0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  0.0000e+00,
          0.0000e+00,  0.0000e+00]])
tensor(2.7395e+18)
torch.Size([256, 256]) None


/var/tmp/pbs.1816038.pbs/ipykernel_2291810/4247516163.py:18: ResourceWarning: unclosed file <_io.BufferedReader name='../../../CNN/Old/ML/src/generation/Real3/psf_36.fits'>
  d=dataset[id_]


0.07144890901145118
-0.30077436008468794
rms 8.721006e-08
tensor([[ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ..., -1.3005e+16,
          2.7868e+15,  1.8579e+15],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ..., -1.5792e+16,
          1.5792e+16, -2.1366e+16],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ..., -4.6447e+15,
          0.0000e+00,  9.2895e+14],
        ...,
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  0.0000e+00,
          0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  0.0000e+00,
          0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  0.0000e+00,
          0.0000e+00,  0.0000e+00]])
tensor(6.9810e+18)
torch.Size([256, 256]) None


/var/tmp/pbs.1816038.pbs/ipykernel_2291810/4247516163.py:18: ResourceWarning: unclosed file <_io.BufferedReader name='../../../CNN/Old/ML/src/generation/Real3/psf_37.fits'>
  d=dataset[id_]


0.07507939159268062
-0.2807916246183595
rms 8.7343324e-08
tensor([[ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ..., -2.5353e+15,
          2.5353e+15,  8.4510e+15],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ..., -1.6902e+15,
          5.0706e+15,  3.3804e+15],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  8.4510e+15,
         -1.8592e+16, -8.4510e+14],
        ...,
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  0.0000e+00,
          0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  0.0000e+00,
          0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  0.0000e+00,
          0.0000e+00,  0.0000e+00]])
tensor(1.0318e+19)
torch.Size([256, 256]) None


/var/tmp/pbs.1816038.pbs/ipykernel_2291810/4247516163.py:18: ResourceWarning: unclosed file <_io.BufferedReader name='../../../CNN/Old/ML/src/generation/Real3/psf_38.fits'>
  d=dataset[id_]


0.07302057269953366
-0.3488528648176725
rms 9.0866315e-08
tensor([[ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  2.9423e+15,
         -5.8846e+15, -8.4065e+14],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ..., -7.9862e+15,
         -4.2033e+15,  7.1456e+15],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ..., -3.3626e+15,
         -4.2033e+15,  4.2033e+15],
        ...,
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  0.0000e+00,
          0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  0.0000e+00,
          0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  0.0000e+00,
          0.0000e+00,  0.0000e+00]])
tensor(3.0612e+18)
torch.Size([256, 256]) None


/var/tmp/pbs.1816038.pbs/ipykernel_2291810/4247516163.py:18: ResourceWarning: unclosed file <_io.BufferedReader name='../../../CNN/Old/ML/src/generation/Real3/psf_39.fits'>
  d=dataset[id_]


0.06494758508779341
-0.31263959954230813
rms 9.162496e-08
tensor([[0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        ...,
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.]])
tensor(2.2445e+17)
torch.Size([256, 256]) None


/var/tmp/pbs.1816038.pbs/ipykernel_2291810/4247516163.py:18: ResourceWarning: unclosed file <_io.BufferedReader name='../../../CNN/Old/ML/src/generation/Real3/psf_40.fits'>
  d=dataset[id_]


0.07574985971814385
-0.3061090296796465
rms 8.921173e-08
tensor([[ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ..., -1.4006e+15,
          1.6007e+15,  1.0805e+16],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ..., -1.2005e+15,
          1.4006e+15,  1.0005e+15],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ..., -8.0037e+14,
          2.6012e+15,  2.2010e+15],
        ...,
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  0.0000e+00,
          0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  0.0000e+00,
          0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  0.0000e+00,
          0.0000e+00,  0.0000e+00]])
tensor(6.6951e+17)
torch.Size([256, 256]) None


/var/tmp/pbs.1816038.pbs/ipykernel_2291810/4247516163.py:18: ResourceWarning: unclosed file <_io.BufferedReader name='../../../CNN/Old/ML/src/generation/Real3/psf_41.fits'>
  d=dataset[id_]


0.07585005334931338
-0.3393882650470914
rms 8.6650836e-08
tensor([[ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ..., -4.6484e+15,
         -1.7431e+15, -4.0673e+15],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ..., -1.1621e+15,
         -4.6484e+15,  1.1621e+15],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  5.2294e+15,
          4.6484e+15, -4.6484e+15],
        ...,
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  0.0000e+00,
          0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  0.0000e+00,
          0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  0.0000e+00,
          0.0000e+00,  0.0000e+00]])
tensor(4.4770e+18)
torch.Size([256, 256]) None


/var/tmp/pbs.1816038.pbs/ipykernel_2291810/4247516163.py:18: ResourceWarning: unclosed file <_io.BufferedReader name='../../../CNN/Old/ML/src/generation/Real3/psf_42.fits'>
  d=dataset[id_]


0.06607513824974376
-0.31726725069347594
rms 8.9744255e-08
tensor([[ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  1.4487e+16,
          5.9265e+15, -1.3170e+15],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  7.2435e+15,
         -1.5804e+16,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  4.6095e+15,
          6.5850e+14,  7.2435e+15],
        ...,
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  0.0000e+00,
          0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  0.0000e+00,
          0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  0.0000e+00,
          0.0000e+00,  0.0000e+00]])
tensor(4.8261e+18)
torch.Size([256, 256]) None


/var/tmp/pbs.1816038.pbs/ipykernel_2291810/4247516163.py:18: ResourceWarning: unclosed file <_io.BufferedReader name='../../../CNN/Old/ML/src/generation/Real3/psf_43.fits'>
  d=dataset[id_]


0.08170890453129687
-0.29166969284233346
rms 8.915034e-08
tensor([[ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ..., -7.6692e+14,
         -2.3008e+15, -6.1354e+15],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  1.5338e+15,
         -3.0677e+15,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  6.1354e+15,
         -3.8346e+15, -6.9023e+15],
        ...,
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  0.0000e+00,
          0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  0.0000e+00,
          0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  0.0000e+00,
          0.0000e+00,  0.0000e+00]])
tensor(5.4965e+18)
torch.Size([256, 256]) None


/var/tmp/pbs.1816038.pbs/ipykernel_2291810/4247516163.py:18: ResourceWarning: unclosed file <_io.BufferedReader name='../../../CNN/Old/ML/src/generation/Real3/psf_44.fits'>
  d=dataset[id_]


0.06105717176296821
-0.27757258180827193
rms 8.6292374e-08
tensor([[ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ..., -3.4296e+15,
          3.0009e+15, -3.4296e+15],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  2.5722e+15,
          8.5740e+14, -1.7148e+15],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ..., -8.5740e+14,
          8.5740e+14,  3.0009e+15],
        ...,
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  0.0000e+00,
          0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  0.0000e+00,
          0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  0.0000e+00,
          0.0000e+00,  0.0000e+00]])
tensor(2.7167e+18)
torch.Size([256, 256]) None


/var/tmp/pbs.1816038.pbs/ipykernel_2291810/4247516163.py:18: ResourceWarning: unclosed file <_io.BufferedReader name='../../../CNN/Old/ML/src/generation/Real3/psf_45.fits'>
  d=dataset[id_]


0.06741236546758955
-0.3176248526415293
rms 9.0516366e-08
tensor([[ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  9.1961e+14,
         -5.5177e+15, -9.1961e+14],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  4.5981e+15,
         -1.7473e+16, -3.2187e+15],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ..., -4.1383e+15,
          5.9775e+15,  5.9775e+15],
        ...,
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  0.0000e+00,
          0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  0.0000e+00,
          0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  0.0000e+00,
          0.0000e+00,  0.0000e+00]])
tensor(3.1777e+18)
torch.Size([256, 256]) None


/var/tmp/pbs.1816038.pbs/ipykernel_2291810/4247516163.py:18: ResourceWarning: unclosed file <_io.BufferedReader name='../../../CNN/Old/ML/src/generation/Real3/psf_46.fits'>
  d=dataset[id_]


0.0757754250457765
-0.30615117907473177
rms 8.8014e-08
tensor([[ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  4.2430e+15,
          7.0716e+15, -2.1215e+15],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ..., -6.3645e+15,
         -4.2430e+15, -4.9501e+15],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ..., -4.9501e+15,
         -2.8287e+15,  7.0716e+14],
        ...,
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  0.0000e+00,
          0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  0.0000e+00,
          0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  0.0000e+00,
          0.0000e+00,  0.0000e+00]])
tensor(4.4162e+18)
torch.Size([256, 256]) None


/var/tmp/pbs.1816038.pbs/ipykernel_2291810/4247516163.py:18: ResourceWarning: unclosed file <_io.BufferedReader name='../../../CNN/Old/ML/src/generation/Real3/psf_47.fits'>
  d=dataset[id_]


0.0646345057475628
-0.3106209476300137
rms 8.9822585e-08
tensor([[ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ..., -4.0010e+15,
          1.0669e+16, -7.3352e+15],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ..., -6.6684e+14,
          1.0003e+16, -2.6674e+15],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  6.6684e+14,
         -9.3358e+15,  0.0000e+00],
        ...,
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  0.0000e+00,
          0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  0.0000e+00,
          0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  0.0000e+00,
          0.0000e+00,  0.0000e+00]])
tensor(3.6376e+18)
torch.Size([256, 256]) None


/var/tmp/pbs.1816038.pbs/ipykernel_2291810/4247516163.py:18: ResourceWarning: unclosed file <_io.BufferedReader name='../../../CNN/Old/ML/src/generation/Real3/psf_48.fits'>
  d=dataset[id_]


0.06906930849481796
-0.30417066909649293
rms 8.826068e-08
tensor([[ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  3.2266e+14,
          2.2586e+15,  1.9360e+15],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ..., -3.2266e+14,
         -5.1626e+15, -3.8719e+15],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  9.6798e+14,
          2.5813e+15, -9.6798e+14],
        ...,
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  0.0000e+00,
          0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  0.0000e+00,
          0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  0.0000e+00,
          0.0000e+00,  0.0000e+00]])
tensor(1.6098e+18)
torch.Size([256, 256]) None


/var/tmp/pbs.1816038.pbs/ipykernel_2291810/4247516163.py:18: ResourceWarning: unclosed file <_io.BufferedReader name='../../../CNN/Old/ML/src/generation/Real3/psf_49.fits'>
  d=dataset[id_]


0.07298035598068964
-0.34137019611080177
rms 9.079419e-08
